OsuJobs/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Osu.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

OsuJobs/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using OsuJobs.Services;
using OsuJobs.Constants;
using OsuJobs.Models;
using OsuJobs.Models.Data;
using OsuJobs.Models.Utilities;

namespace OsuJobs.Controllers
{
    public class JobsController : Controller
    {
        private readonly JobsService jobService= new JobsService();

        /// <summary>
        /// Retreives the postings from the
        /// job postings service and returns them to the 
        /// partial view _JobPostings
        /// </summary>
        /// <returns></returns>
        public ActionResult Postings()
        {
            var postings = this.jobService.GetJobs().OrderBy(x => x.Title);
            this.Session[SessionKeys.JobPostings] = postings;

            return this.PartialView("_JobPostings", postings);
        }
        /// <summary>
        /// Takes in a list of filters and runs them against the postings in session
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        public ActionResult FilterJobs(List<JobFilter> filter)
        {
            var jobs = this.Session[SessionKeys.JobPostings] as IEnumerable<JobPosting>;

            //if for some reason the session cache is empty, e.g. session timeout,
            //pull down another copy of the jobs and cache it in session
            if (jobs == null)
            {
                jobs = this.jobService.GetJobs();
                this.Session[SessionKeys.JobPostings] = jobs;
            }

            var filteredJobs = new List<JobPosting>();

            //filter results
            this.FilterJobs(filteredJobs, jobs, filter);

            return this.PartialView("_Postings", filteredJobs.Distinct(new JobPostingComparer()).OrderBy(x => x.Title));
        }

        /// <summary>
        /// Sorts the job postings based on the sort on property and direction
        /// </summary>
        /// <param name="filter"></param>
        /// <param name="sort"></param>
        /// <returns></returns>
        public ActionResult SortJobs(List<JobFilter> filter, JobSort sort)
        {
            var jobs = this.Session[SessionKeys.JobPostings] as IEnumerable<JobPosting>;

            //if for some reason the session cache is empty, e.g. session timeout,
            //pull down another copy of the jobs and cache it in session
            if (jobs == null)
            {
                jobs = this.jobService.GetJobs();
                this.Session[SessionKeys.JobPostings] = jobs;
            }

            var filteredJobs = new List<JobPosting>();

            this.FilterJobs(filteredJobs, jobs, filter);

            ViewBag.SortBy = sort;

            switch (sort.SortBy)
            {
                case JobProperty.Department:
                    if (sort.Direction == DirectionSort.Asc)
                    {
                        return this.PartialView("_JustPostings", filteredJobs.Distinct(new JobPostingComparer()).OrderBy(x => x.Author));
                    }
                    else
                    {
                        return this.PartialView("_JustPostings", filteredJobs.Distinct(new JobPostingComparer()).OrderByDescending(x => x.Author));
                    }
                case JobProperty.Title:
                    if (sort.Direction == DirectionSort.Asc)
                    {
                        return this.PartialView("_JustPostings", filteredJobs.Distinct(new JobPostingComparer()).OrderBy(x => x.Title));
                    }
                    else
                    {
                        return this.PartialView("_JustPostings", filteredJobs.Distinct(new JobPostingComparer()).OrderByDescending(x => x.Title));
                    }
                default:
                    throw new Exception(string.Format(ExceptionResources.ParameterNullOrUnknown, "Sort By"));
            }
        }

        /// <summary>
        /// Takes in referenced list for the results and the orignial data along with 
        /// a list of filters to apply to the original data 
        /// </summary>
        /// <param name="filteredJobs"></param>
        /// <param name="jobs"></param>
        /// <param name="filter"></param>
        private void FilterJobs(List<JobPosting> filteredJobs, IEnumerable<JobPosting> jobs, List<JobFilter> filter)
        {
            if (filter == null || !filter.Any())
            {
                //if nothing is selected then return everything
                filteredJobs.AddRange(jobs);
            }
            else
            {
                filter.ForEach(delegate(JobFilter filtering)
                {
                    //Author should equal department
                    if (filtering.Type == JobProperty.Title)
                    {
                        filteredJobs.AddRange(jobs.Where(x => x.Title.Equals(filtering.Value, StringComparison.InvariantCultureIgnoreCase)));
                    }
                    else
                    {
                        filteredJobs.AddRange(jobs.Where(x => x.Author.Equals(filtering.Value, StringComparison.InvariantCultureIgnoreCase)));
                    }
                });
            }
        }

        /// <summary>
        /// Retrieves the remaining details from the session cache, if it exists,
        /// and binds it to a details view for javascript to display
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult JobDetails(string id)
        {
            var jobs = this.Session[SessionKeys.JobPostings] as IEnumerable<JobPosting>;

            //if for some reason the session cache is empty, e.g. session timeout,
            //pull down another copy of the jobs and cache it in session
            if (jobs == null)
            {
                jobs = this.jobService.GetJobs();
                this.Session[SessionKeys.JobPostings] = jobs;
            }

            //check to make sure the job still exists if 
            //a new set was pulled down
            if(!jobs.Any(x => x.Id == id))
            {
                return this.PartialView("_DetailsNotFound");
            }

            return this.PartialView("_Details", jobs.Single(x => x.Id == id));
        }

    }
}

OsuJobs/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Osu Job Postings";
}

@Html.Action("Postings", "Jobs")

OsuJobs/Views/Jobs/_Details.cshtml
@model OsuJobs.Models.JobPosting
<a href="@Model.Url" target="_blank">More Details</a>
<div class="jobDates">
    Modified On @Model.LastUpdatedFormatted<br />
    Published On @Model.PublishedFormatted
</div>
<br />
<br />
<div class="jobBody">
    @Html.Raw(Model.Content)
</div>

OsuJobs/Views/Jobs/_DetailsNotFound.cshtml
<div class="defaultText centeredText">
    Details for the job you've selected are no longer available. We apologize for any inconvenience, please refresh and try again.
</div>

OsuJobs/Views/Jobs/_Filters.cshtml
@using OsuJobs.Models.Data
@model IEnumerable<OsuJobs.Models.JobPosting>

@{
    var jobTitles = Model.Select(x => x.Title).Distinct().ToList();
    var postingDepartments = Model.Select(x => x.Author).Distinct().ToList();
    postingDepartments.Sort();
    jobTitles.Sort();
}

@if (Model != null && Model.Any())
{  
    <input class="button centeredButton" type="button" value="Reset" onclick="filterReset()" />
    <br />
    <div class="filterTitle">
        Filter By Department
    </div>
    <div class="aFilterContainer">
        @foreach(var department in postingDepartments)
        {
            <div class="aFilter" data-filter-by="@JobProperty.Department" data-filter-by-value="@department">
                @department
            </div>
        }
    </div>
    <br />
    <div class="filterTitle">
       Filter by Job Title
    </div>
    <div class="aFilterContainer">
        @foreach(var title in jobTitles)
        {
            <div class="aFilter" data-filter-by="@JobProperty.Title" data-filter-by-value="@title">
                @title
            </div>
        }
    </div>
}
else
{
    <div class="defaultText">No Filters Available</div>
}

<script type="text/javascript">
    $(function () {
        $(".aFilter").click(function () {
            if ($(this).hasClass("aFilterSelected")) {
                $(this).removeClass("aFilterSelected");
            } else {
                $(this).addClass("aFilterSelected");
            }

            applyFilterAndSearch();
        });
    });

    function filterReset() {
        $(".aFilter").removeClass("aFilterSelected");
        applyFilterAndSearch();
    }

    function applyFilterAndSearch() {
        var parameters = getFilters();

        if ($("#loading").length == 0) {
            $("#actualPostings").prepend("<div class='job' id='loading'><img src='/Content/images/ajax-loader.gif' class='loaderImage' /></div>");
        }

        $.ajax({
            contentType: 'application/json; charset=utf-8',
            type: "POST",
            data: JSON.stringify({ 'filter': parameters }),
            url: "@Url.Action("FilterJobs")",
            success: function (data, textStatus, jqXHR) {
                $("#jobPostings").html(data);
            },
            fail: function () {
                $("#error").html("An unexpected error has occured please refresh and try again.");
            }
        });
    }

    function getFilters() {
        var parameters = [];

        $(".aFilterSelected").each(function () {
            parameters.push({
                Type: $(this).attr("data-filter-by"),
                Value: $(this).attr("data-filter-by-value")
            });
        });

        return parameters;
    }
</script>

OsuJobs/Views/Jobs/_Job.cshtml
@model OsuJobs.Models.JobPosting
<div data-id="@Model.Id" data-title="@Model.Title" data-department="@Model.Author" class="job">
    <div class="jobTitle">
        @Html.Raw(Model.Title)
    </div>
    <div class="jobAuthor">
        @Html.Raw(Model.Author)
    </div>
    <div class="jobContent"></div>
</div>
<div data-id="@Model.Id" class="jobDetails"></div>

OsuJobs/Views/Jobs/_JobPostings.cshtml
@model IEnumerable<OsuJobs.Models.JobPosting>
<div class="jobFilter">
    @Html.Partial("_Filters", Model)
</div>
<div id="jobPostings" class="jobBoard">
    @Html.Partial("_Postings", Model);
</div>

OsuJobs/Views/Jobs/_JustPostings.cshtml
@using OsuJobs.Models.Data;
@using OsuJobs.Models;
@model IEnumerable<OsuJobs.Models.JobPosting>

@if (Model != null && Model.Any())
{
    foreach (var job in Model)
    {
        @Html.Partial("_Job", job)
    }
}
else
{
    <div class="defaultText">No Job Postings Found</div>
}
<script type="text/javascript">
    $(function () {
        $(".job").click(function () {
            if ($(".jobDetails[data-id=" + $(this).attr("data-id") + "]").is(":visible")) {
                $(".jobDetails[data-id=" + $(this).attr("data-id") + "]").slideUp(500, function () {
                    $(this).empty();
                });

                $(this).css("background-color", "#fff");
                $(this).find(".jobTitle").css("color","#0026ff");
                $(this).find(".jobAuthor").css("color","#4e4e4e");
            } else {
                $(".jobDetails:visible").slideUp(200, function () {
                    $(this).empty();
                    var $jobContext = $(".job[data-id=" + $(this).attr("data-id") + "]");
                    $jobContext.css("background-color", "#fff");
                    $jobContext.find(".jobTitle").css("color", "#0026ff");
                    $jobContext.find(".jobAuthor").css("color", "#4e4e4e");
                });

                var $jobContext = $(this).css("background-color", "#BB2025");
                $jobContext.find(".jobTitle").css("color", "#fff");
                $jobContext.find(".jobAuthor").css("color", "#fff");

                $(".jobDetails[data-id=" + $(this).attr("data-id") + "]").load("@Url.Action("JobDetails", new { id = "UNIQUEID" })".replace("UNIQUEID", $(this).attr("data-id")),
                    function () {
                        $(this).slideDown(500);
                    });
            }
        });
    });
</script>

OsuJobs/Views/Jobs/_Postings.cshtml
@using OsuJobs.Models.Data;
@using OsuJobs.Models;
@model IEnumerable<OsuJobs.Models.JobPosting>
@{
    var sort = new JobSort();

    if (ViewBag.SortBy != null)
    {
        sort = (JobSort)ViewBag.SortBy;
    } 
}
<div class="controlPanel">
    <div class="descriptionPanel">
        Sort By:
    </div>
    <div data-sort-direction="@DirectionSort.Dsc" data-sort-property="@JobProperty.Department" class="sortPanel">
        Department <img src="@Url.Content("~/Content/images/downarrow.png")" class="sortArrow" />
    </div>
    <div data-sort-direction="@DirectionSort.Dsc" data-sort-property="@JobProperty.Title" class="sortPanel">
        Title <img src="@Url.Content("~/Content/images/downarrow.png")" class="sortArrow" />
    </div>
</div>
<div id="actualPostings" class="innerJobPostings">
    @Html.Partial("_JustPostings", Model)
</div>
<script type="text/javascript">
    $(function () {
        $(".sortPanel").click(function () {
            if ($("#loading").length == 0) {
                $("#actualPostings").prepend("<div class='job' id='loading'><img src='/Content/images/ajax-loader.gif' class='loaderImage' /></div>");
            }

            if ($(this).attr("data-sort-direction") == "@DirectionSort.Dsc") {
                $(this).attr("data-sort-direction", "@DirectionSort.Asc").find(".sortArrow").attr("src", "/Content/images/uparrow.png");
            } else {
                $(this).attr("data-sort-direction", "@DirectionSort.Dsc").find(".sortArrow").attr("src", "/Content/images/downarrow.png");
            }

            $.ajax({
                contentType: 'application/json; charset=utf-8',
                type: "POST",
                data: JSON.stringify({
                    'filter': getFilters(),
                    'sort': getSortBy(this)
                }),
                url: "@Url.Action("SortJobs")",
                success: function (data, textStatus, jqXHR) {
                    $("#actualPostings").html(data);
                },
                fail: function () {
                    $("#error").html("An unexpected error has occured please refresh and try again.");
                }
            });
        });
    });

    function getSortBy(context) {
        return {
            Direction: $(context).attr("data-sort-direction"),
            SortBy: $(context).attr("data-sort-property")
        };
    }
</script>

OsuJobs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/Style.css")">
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.scrollTo.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/OsuJobs.js")"></script>
</head>
<body>
    <div id="main">    
        <div class="title"> 
            <img id="mainLogo" src="@Url.Content("~/Content/images/osuLogo.png")" />
            <div class="subTitle">
                Jobs
            </div>
        </div>
        <div id="error"></div>
        @RenderBody()
        <div id="scrollToTop">
            Top
        </div>
    </div>
</body>
</html>